// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkw2IlagW96CRJ_8lmHrI8tMrlgyF5U20',
    appId: '1:146545034456:android:0f806671310944fbd203ad',
    messagingSenderId: '146545034456',
    projectId: 'dermai-b5963',
    storageBucket: 'dermai-b5963.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5pII-IX9oD_rVn5SRvK3c_MBL1SCSMPE',
    appId: '1:146545034456:ios:bf53eb5f4fac8376d203ad',
    messagingSenderId: '146545034456',
    projectId: 'dermai-b5963',
    storageBucket: 'dermai-b5963.firebasestorage.app',
    androidClientId: '146545034456-t6fptjgh6lf6j6rkt63d6nqilihpl9l9.apps.googleusercontent.com',
    iosClientId: '146545034456-ec3l27jsgvahsarthrp947n0qmceitbn.apps.googleusercontent.com',
    iosBundleId: 'com.example.demodermaicare',
  );
}
